{ pkgs, pkgs-unstable, ... }: {
  nixpkgs.config.permittedInsecurePackages = [ 
    "dotnet-runtime-7.0.20"
     "electron-33.4.11"
  ];
  fonts.packages = with pkgs; [
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-emoji
    liberation_ttf
    fira-code
    fira-code-symbols
    mplus-outline-fonts.githubRelease
    dina-font
    proggyfonts
    corefonts
    vistafonts
    nerd-fonts._3270
    nerd-fonts.agave
    nerd-fonts.anonymice
    nerd-fonts.arimo
    nerd-fonts.aurulent-sans-mono
    nerd-fonts.bigblue-terminal
    nerd-fonts.bitstream-vera-sans-mono
    nerd-fonts.blex-mono
    nerd-fonts.caskaydia-cove
    nerd-fonts.caskaydia-mono
    nerd-fonts.code-new-roman
    nerd-fonts.comic-shanns-mono
    nerd-fonts.commit-mono
    nerd-fonts.cousine
    nerd-fonts.d2coding
    nerd-fonts.daddy-time-mono
    nerd-fonts.departure-mono
    nerd-fonts.dejavu-sans-mono
    nerd-fonts.droid-sans-mono
    nerd-fonts.envy-code-r
    nerd-fonts.fantasque-sans-mono
    nerd-fonts.fira-code
    nerd-fonts.fira-mono
    nerd-fonts.geist-mono
    nerd-fonts.go-mono
    nerd-fonts.gohufont
    nerd-fonts.hack
    nerd-fonts.hasklug
    nerd-fonts.heavy-data
    nerd-fonts.hurmit
    nerd-fonts.im-writing
    nerd-fonts.inconsolata
    nerd-fonts.inconsolata-go
    nerd-fonts.inconsolata-lgc
    nerd-fonts.intone-mono
    nerd-fonts.iosevka
    nerd-fonts.iosevka-term
    nerd-fonts.iosevka-term-slab
    nerd-fonts.jetbrains-mono
    nerd-fonts.lekton
    nerd-fonts.liberation
    nerd-fonts.lilex
    nerd-fonts.martian-mono
    nerd-fonts.meslo-lg
    nerd-fonts.monaspace
    nerd-fonts.monofur
    nerd-fonts.monoid
    nerd-fonts.mononoki
    nerd-fonts.mplus
    nerd-fonts.noto
    nerd-fonts.open-dyslexic
    nerd-fonts.overpass
    nerd-fonts.profont
    nerd-fonts.proggy-clean-tt
    nerd-fonts.recursive-mono
    nerd-fonts.roboto-mono
    nerd-fonts.shure-tech-mono
    nerd-fonts.sauce-code-pro
    nerd-fonts.space-mono
    nerd-fonts.symbols-only
    nerd-fonts.terminess-ttf
    nerd-fonts.tinos
    nerd-fonts.ubuntu
    nerd-fonts.ubuntu-mono
    nerd-fonts.ubuntu-sans
    nerd-fonts.victor-mono
    nerd-fonts.zed-mono
  ];

  environment.systemPackages = [ 
    pkgs-unstable.vintagestory 
    pkgs.icewm
    pkgs.SDL2
    pkgs.SDL2_ttf
    pkgs.raylib
    pkgs.gnumake
    pkgs.gdb
    pkgs.gimp
    pkgs-unstable.lutris # Lutris is a video game preservation platform#
    pkgs.nerd-fonts._3270
    pkgs.nerd-fonts.agave
    pkgs.nerd-fonts.anonymice
    pkgs.nerd-fonts.arimo
    pkgs.nerd-fonts.aurulent-sans-mono
    pkgs.nerd-fonts.bigblue-terminal
    pkgs.nerd-fonts.bitstream-vera-sans-mono
    pkgs.nerd-fonts.blex-mono
    pkgs.nerd-fonts.caskaydia-cove
    pkgs.nerd-fonts.caskaydia-mono
    pkgs.nerd-fonts.code-new-roman
    pkgs.nerd-fonts.comic-shanns-mono
    pkgs.nerd-fonts.commit-mono
    pkgs.nerd-fonts.cousine
    pkgs.nerd-fonts.d2coding
    pkgs.nerd-fonts.daddy-time-mono
    pkgs.nerd-fonts.departure-mono
    pkgs.nerd-fonts.dejavu-sans-mono
    pkgs.nerd-fonts.droid-sans-mono
    pkgs.nerd-fonts.envy-code-r
    pkgs.nerd-fonts.fantasque-sans-mono
    pkgs.nerd-fonts.fira-code
    pkgs.nerd-fonts.fira-mono
    pkgs.nerd-fonts.geist-mono
    pkgs.nerd-fonts.go-mono
    pkgs.nerd-fonts.gohufont
    pkgs.nerd-fonts.hack
    pkgs.nerd-fonts.hasklug
    pkgs.nerd-fonts.heavy-data
    pkgs.nerd-fonts.hurmit
    pkgs.nerd-fonts.im-writing
    pkgs.nerd-fonts.inconsolata
    pkgs.nerd-fonts.inconsolata-go
    pkgs.nerd-fonts.inconsolata-lgc
    pkgs.nerd-fonts.intone-mono
    pkgs.nerd-fonts.iosevka
    pkgs.nerd-fonts.iosevka-term
    pkgs.nerd-fonts.iosevka-term-slab
    pkgs.nerd-fonts.jetbrains-mono
    pkgs.nerd-fonts.lekton
    pkgs.nerd-fonts.liberation
    pkgs.nerd-fonts.lilex
    pkgs.nerd-fonts.martian-mono
    pkgs.nerd-fonts.meslo-lg
    pkgs.nerd-fonts.monaspace
    pkgs.nerd-fonts.monofur
    pkgs.nerd-fonts.monoid
    pkgs.nerd-fonts.mononoki
    pkgs.nerd-fonts.mplus
    pkgs.nerd-fonts.noto
    pkgs.nerd-fonts.open-dyslexic
    pkgs.nerd-fonts.overpass
    pkgs.nerd-fonts.profont
    pkgs.nerd-fonts.proggy-clean-tt
    pkgs.nerd-fonts.recursive-mono
    pkgs.nerd-fonts.roboto-mono
    pkgs.nerd-fonts.shure-tech-mono
    pkgs.nerd-fonts.sauce-code-pro
    pkgs.nerd-fonts.space-mono
    pkgs.nerd-fonts.symbols-only
    pkgs.nerd-fonts.terminess-ttf
    pkgs.nerd-fonts.tinos
    pkgs.nerd-fonts.ubuntu
    pkgs.nerd-fonts.ubuntu-mono
    pkgs.nerd-fonts.ubuntu-sans
    pkgs.nerd-fonts.victor-mono
    pkgs.nerd-fonts.zed-mono
  ];
}
